name: space_data_explorer
version: 0.3.0

description: An app to explore space data from various sources.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^8.0.5
  hrk_logging: ^0.1.0-pre.2
  hrk_nasa_apis: ^0.1.0-pre.3
  hrk_batteries: ^0.1.0-pre.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hrk_analysis: ^0.1.0-pre.1
  hrk_flutter_test_batteries: ^0.1.0-pre.1
  import_sorter:
    git:
      url: https://github.com/fluttercommunity/import_sorter.git
      ref: f350497a11b1285c695595049e95a420068e7a9f
  path_provider: ^2.0.11

flutter:
  uses-material-design: true

import_sorter:
  comments: false
