name: space_data_explorer
version: 0.4.0-dev

description: An app to explore space data from various sources.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  meta: ^1.9.1
  hrk_logging: ^0.1.0
  hrk_nasa_apis: ^0.1.0
  hrk_batteries: ^0.1.0
  go_router: ^8.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hrk_analysis: ^0.1.0
  hrk_flutter_test_batteries: ^0.1.0
  import_sorter:
    git:
      url: https://github.com/fluttercommunity/import_sorter.git
      ref: f350497a11b1285c695595049e95a420068e7a9f
  path_provider: ^2.0.11

flutter:
  uses-material-design: true

import_sorter:
  comments: false
