name: space_data_explorer
version: 0.5.0

description: An app to explore space data from various sources.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.9.1
  cupertino_icons: ^1.0.2
  hrk_batteries: '>=0.3.0 <1.0.0'
  hrk_logging: '>=0.1.3 <1.0.0'
  hrk_nasa_apis: '>=0.12.0 <1.0.0'
  hrk_settings_list:
    path: 'packages/hrk_settings_list'
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^10.0.0
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.5
  path_provider: ^2.0.11
  flutter_staggered_grid_view: ^0.7.0
  flutter_keyboard_visibility: ^5.4.1
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_analytics: ^10.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  hrk_analysis: '>=0.1.0 <1.0.0'
  hrk_flutter_test_batteries: '>=0.7.0 <1.0.0'
  import_sorter:
    git:
      url: https://github.com/fluttercommunity/import_sorter.git
      ref: f350497a11b1285c695595049e95a420068e7a9f
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  go_router_builder: ^2.2.4
  flutterfire_cli: '>=0.3.0-dev.16 <1.0.0'

# dependency_overrides:
#   hrk_batteries:
#     path: '../../dart/packages/hrk_batteries'
#   hrk_flutter_test_batteries:
#     path: '../packages/hrk_flutter_test_batteries'
#   hrk_nasa_apis:
#     path: '../../dart/packages/hrk_nasa_apis'

flutter:
  uses-material-design: true
  generate: true

import_sorter:
  comments: false
  ignored_files:
    - '.*\.mocks\.dart'
    - test[/\\]src[/\\]config[/\\]hydrated_bloc\.dart
    - test[/\\]src[/\\]config[/\\]dio_response\.dart
    - test[/\\]src[/\\]nasa[/\\]cad[/\\]sbdb_cad_api\.dart
