name: hrk_nasa_apis
description: Dart client for NASA Open APIs by HRK.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.5

dependencies:
  dio: ^5.2.1+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  hrk_logging: 
    path: ../hrk_logging

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0
